import { fmtCurrency, fmtPct, fmtRoas, fmtNum } from './metricCalculator.js';

export function generateWeeklyReport(summary, campaigns, recommendations, dateLabel) {
  if (!summary) return '';

  const bestCampaign = [...campaigns]
    .filter(c => (c.orders ?? 0) > 0 && c.roas != null)
    .sort((a, b) => (b.roas ?? 0) - (a.roas ?? 0))[0];

  const worstCampaign = [...campaigns]
    .filter(c => (c.spend ?? 0) > 0)
    .sort((a, b) => {
      // Prefer campaigns with spend and no orders, then by ACoS
      const aScore = (a.orders ?? 0) === 0 ? Infinity : (a.acos === 'NO_SALES' ? 999 : (a.acos ?? 999));
      const bScore = (b.orders ?? 0) === 0 ? Infinity : (b.acos === 'NO_SALES' ? 999 : (b.acos ?? 999));
      return bScore - aScore;
    })[0];

  const highIssues = recommendations.filter(r => r.severity === 'HIGH');
  const opportunities = recommendations.filter(r => r.severity === 'OPPORTUNITY');

  const issueLines = highIssues.slice(0, 3).map(r => `• ${r.headline}`).join('\n');
  const actionLines = recommendations.slice(0, 5).map(r => `• ${r.action}`).join('\n');

  const dominantType = highIssues.length > opportunities.length ? 'reduce-waste' : 'scale-winners';
  const focusSentence = dominantType === 'reduce-waste'
    ? 'Focus on eliminating wasted spend: add negative keywords, pause zero-order campaigns, and tighten targeting.'
    : 'Focus on scaling profitable campaigns: increase budgets on winners and move converting search terms to Exact Match.';

  return `Amazon Ads Weekly Summary${dateLabel ? ` — ${dateLabel}` : ''}

PERFORMANCE OVERVIEW
────────────────────────────────
Total Spend:       ${fmtCurrency(summary.totalSpend)}
Total Sales:       ${fmtCurrency(summary.totalSales)}
Average ACoS:      ${summary.avgAcos === 'NO_SALES' ? 'No Sales' : fmtPct(summary.avgAcos)}
ROAS:              ${fmtRoas(summary.avgRoas)}
Total Orders:      ${fmtNum(summary.totalOrders)}
Total Clicks:      ${fmtNum(summary.totalClicks)}
Total Impressions: ${fmtNum(summary.totalImpressions)}
Avg CTR:           ${fmtPct(summary.avgCtr)}
Avg CPC:           ${fmtCurrency(summary.avgCpc)}
Conversion Rate:   ${fmtPct(summary.avgCvr)}

HIGHLIGHTS
────────────────────────────────
Best Campaign:   ${bestCampaign ? `${bestCampaign.campaignName} (ROAS: ${fmtRoas(bestCampaign.roas)})` : 'N/A'}
Worst Campaign:  ${worstCampaign ? `${worstCampaign.campaignName} (${worstCampaign.orders === 0 ? 'No orders' : `ACoS: ${fmtPct(worstCampaign.acos)}`})` : 'N/A'}

MAIN ISSUES FOUND
────────────────────────────────
${issueLines || '• No critical issues detected'}

ACTIONS RECOMMENDED
────────────────────────────────
${actionLines || '• Continue monitoring current performance'}

NEXT WEEK FOCUS
────────────────────────────────
• ${focusSentence}

────────────────────────────────
Generated by FUFLD PPC Pilot`;
}
